In [2]:
import pandas as pd
import pylab as pl
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
train_df = pd.read_csv("train.csv")
train_df.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 785 columns]

In [3]:
X_data=train_df.iloc[:,1:]
X_data.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 784 columns]

In [4]:
Y_data=train_df.iloc[:,0]
Y_data.head()

0    1
1    0
2    1
3    4
4    0
Name: label, dtype: int64

In [5]:
from sklearn.cross_validation import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split( X_data, Y_data, test_size=0.8)

C:\Users\Aloha\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [6]:
total=np.zeros(10)
for i in range(0,len(Y_test)):
    total[Y_test.iloc[i]]+=1
print(total)

[403. 488. 471. 404. 405. 387. 418. 437. 398. 402.]


In [8]:
#SVM

In [11]:
from sklearn import svm
clf = svm.SVC(kernel='linear')
clf.fit(X_train, Y_train) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [12]:
Y_aftersvc = clf.predict(X_test)
total=np.zeros(10)
for i in range(0,len(Y_test)):
    total[Y_aftersvc[i]]+=1
print(total)
total=np.zeros(10)
for i in range(0,len(Y_test)):
    total[Y_test.iloc[i]]+=1
print(total)

[430. 513. 442. 384. 446. 385. 446. 412. 364. 391.]
[409. 472. 451. 414. 402. 390. 430. 442. 396. 407.]


In [13]:
total=0
for i in range(0,len(Y_test)):
    if Y_test.iloc[i]==Y_aftersvc[i]:
        """print(str(Y_test.iloc[i])+"  "+str(Y_aftersvc[i]))"""
        total+=1
print(total/len(Y_test))

0.8860669356752907


In [14]:
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(Y_test, Y_aftersvc)

0.8860669356752907

In [15]:
from sklearn import svm
clf = svm.SVC(kernel='poly')
clf.fit(X_train, Y_train) 
Y_aftersvc = clf.predict(X_test)
total=np.zeros(10)
for i in range(0,len(Y_test)):
    total[Y_aftersvc[i]]+=1
print(total)
total=np.zeros(10)
for i in range(0,len(Y_test)):
    total[Y_test.iloc[i]]+=1
print(total)
total=0
for i in range(0,len(Y_test)):
    if Y_test.iloc[i]==Y_aftersvc[i]:
        """print(str(Y_test.iloc[i])+"  "+str(Y_aftersvc[i]))"""
        total+=1
print(total/len(Y_test))
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(Y_test, Y_aftersvc)

[412. 619. 430. 383. 410. 379. 432. 388. 368. 392.]
[409. 472. 451. 414. 402. 390. 430. 442. 396. 407.]
0.8905767861381438


0.8905767861381438

In [16]:
from sklearn import svm
clf = svm.SVC(kernel='rbf')
clf.fit(X_train, Y_train) 
Y_aftersvc = clf.predict(X_test)
total=np.zeros(10)
for i in range(0,len(Y_test)):
    total[Y_aftersvc[i]]+=1
print(total)
total=np.zeros(10)
for i in range(0,len(Y_test)):
    total[Y_test.iloc[i]]+=1
print(total)
total=0
for i in range(0,len(Y_test)):
    if Y_test.iloc[i]==Y_aftersvc[i]:
        """print(str(Y_test.iloc[i])+"  "+str(Y_aftersvc[i]))"""
        total+=1
print(total/len(Y_test))
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(Y_test, Y_aftersvc)

[   0.    0. 4213.    0.    0.    0.    0.    0.    0.    0.]
[409. 472. 451. 414. 402. 390. 430. 442. 396. 407.]
0.10704960835509138


0.10704960835509138

In [9]:
from sklearn.tree import DecisionTreeClassifier
drugTree = DecisionTreeClassifier(criterion="entropy", max_depth = 4)
drugTree # it shows the default parameters

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [10]:
drugTree.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [15]:
Y_afterdecision = drugTree.predict(X_test)

In [18]:
total=np.zeros(10)
for i in range(0,len(Y_test)):
    total[Y_afterdecision[i]]+=1
print(total)
total=np.zeros(10)
for i in range(0,len(Y_test)):
    total[Y_test.iloc[i]]+=1
print(total)
total=0
for i in range(0,len(Y_test)):
    if Y_test.iloc[i]==Y_afterdecision[i]:
        """print(str(Y_test.iloc[i])+"  "+str(Y_afterdecision[i]))"""
        total+=1
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(Y_test, Y_afterdecision)

[547. 577. 399. 392. 612. 179. 398. 525. 336. 248.]
[403. 488. 471. 404. 405. 387. 418. 437. 398. 402.]


0.5900783289817232

In [23]:
from sklearn.tree import DecisionTreeClassifier
drugTree = DecisionTreeClassifier(criterion="gini",max_depth = None)
drugTree # it shows the default parameters
drugTree.fit(X_train,Y_train)
Y_afterdecision = drugTree.predict(X_test)
total=np.zeros(10)
for i in range(0,len(Y_test)):
    total[Y_afterdecision[i]]+=1
print(total)
total=np.zeros(10)
for i in range(0,len(Y_test)):
    total[Y_test.iloc[i]]+=1
print(total)
total=0
for i in range(0,len(Y_test)):
    if Y_test.iloc[i]==Y_afterdecision[i]:
        """print(str(Y_test.iloc[i])+"  "+str(Y_afterdecision[i]))"""
        total+=1
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(Y_test, Y_afterdecision)

[412. 498. 444. 386. 376. 429. 405. 452. 394. 417.]
[403. 488. 471. 404. 405. 387. 418. 437. 398. 402.]


0.6786138143840493

In [33]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import jaccard_similarity_score
for k in range(1,21):
    #Train Model and Predict  
    neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,Y_train)
    Y_afterKNN = neigh.predict(X_test)
    print("k="+str(k))
    total=np.zeros(10)
    for i in range(0,len(Y_test)):
        total[Y_afterKNN[i]]+=1
    print(total)
    total=np.zeros(10)
    for i in range(0,len(Y_test)):
        total[Y_test.iloc[i]]+=1
    print(total)
    print(jaccard_similarity_score(Y_test, Y_afterKNN))

k=1
[421. 554. 406. 398. 372. 400. 437. 459. 352. 414.]
[403. 488. 471. 404. 405. 387. 418. 437. 398. 402.]
0.8803702824590554
k=2
[466. 600. 409. 448. 439. 373. 405. 471. 294. 308.]
[403. 488. 471. 404. 405. 387. 418. 437. 398. 402.]
0.8592451934488488
k=3
[453. 591. 393. 415. 389. 361. 429. 423. 321. 438.]
[403. 488. 471. 404. 405. 387. 418. 437. 398. 402.]
0.8756230714455258
k=4
[448. 610. 381. 415. 392. 358. 428. 445. 328. 408.]
[403. 488. 471. 404. 405. 387. 418. 437. 398. 402.]
0.8751483503441728
k=5
[440. 603. 378. 415. 372. 359. 432. 431. 333. 450.]
[403. 488. 471. 404. 405. 387. 418. 437. 398. 402.]
0.8711132209826726
k=6
[449. 609. 382. 416. 383. 355. 429. 433. 323. 434.]
[403. 488. 471. 404. 405. 387. 418. 437. 398. 402.]
0.8699264182292903
k=7
[439. 612. 381. 415. 368. 350. 437. 434. 325. 452.]
[403. 488. 471. 404. 405. 387. 418. 437. 398. 402.]
0.8694516971279374
k=8
[442. 620. 377. 416. 377. 344. 431. 432. 323. 451.]
[403. 488. 471. 404. 405. 387. 418. 437. 398. 402.]
0.8