In [1]:
import pandas as pd
import pylab as pl
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
train_df = pd.read_csv("train.csv")
train_df.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 785 columns]

In [2]:
X_data=train_df.iloc[:,1:]
X_data.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 784 columns]

In [3]:
Y_data=train_df.iloc[:,0]
Y_data.head()

0    1
1    0
2    1
3    4
4    0
Name: label, dtype: int64

In [4]:
from sklearn.cross_validation import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split( X_data, Y_data, test_size=0.4)

C:\Users\Aloha\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [5]:
total=np.zeros(10)
for i in range(0,len(Y_test)):
    total[Y_test.iloc[i]]+=1
print(total)

[192. 233. 217. 196. 218. 205. 243. 205. 193. 205.]


In [6]:
from sklearn import svm
clf = svm.SVC(kernel='rbf')
clf.fit(X_train, Y_train) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [7]:
Y_aftersvc = clf.predict(X_test)
total=np.zeros(10)
for i in range(0,len(Y_test)):
    total[Y_aftersvc[i]]+=1
print(total)
total=np.zeros(10)
for i in range(0,len(Y_test)):
    total[Y_test.iloc[i]]+=1
print(total)

[   0.    0. 2107.    0.    0.    0.    0.    0.    0.    0.]
[192. 233. 217. 196. 218. 205. 243. 205. 193. 205.]


In [8]:
total=0
for i in range(0,len(Y_test)):
    if Y_test.iloc[i]==Y_aftersvc[i]:
        """print(str(Y_test.iloc[i])+"  "+str(Y_aftersvc[i]))"""
        total+=1
print(total/len(Y_test))

0.10299003322259136


In [9]:
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(Y_test, Y_aftersvc)

0.10299003322259136